# Generated by Django 5.0.2 on 2024-03-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('provider', 'Provider')], default='customer', max_length=50),
        ),
    ]
