# Generated by Django 5.0.2 on 2024-03-19 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_initial'),
        ('user', '0002_alter_usertype_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.servicebooking'),
            preserve_default=False,
        ),
    ]
