# Generated by Django 5.0.2 on 2024-03-20 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_feedback_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
